/**
 * Business type constants for user registration
 * These values are used in the registration form and sent to the backend
 */
export const BUSINESS_TYPES = {
  DENTAL_PRACTICE: "Dental_Practice",
  PERSONAL_CUSTOMER: "Personal_Customer",
  EDUCATIONAL_OR_GOVERNMENT_DENTAL_FACILITY: "Educational_or_Government_Dental_Facility",
  DENTAL_SERVICE_INDUSTRY: "Dental_Service_Industry",
  OTHER_HEALTHCARE_BUSINESS: "Other_Healthcare_Business",
  MANUFACTURER: "Manufacturer",
  TECHNOLOGY: "Technology",
  AEROSPACE: "Aerospace",
  SERVICE_INDUSTRY: "Service_Industry",
  GOVERNMENT_AGENCY: "Government_Agency",
  EDUCATION_SCHOOL_COLLEGES: "Education_School_Colleges",
  NON_PROFIT_CHARITY: "Non_profit_Charity",
  SPORT_LEISURE: "Sport_Leisure",
  RELIGIOUS_SPIRITUAL: "Religious_Spiritual",
  OTHER: "Other",
} as const

/**
 * Business type labels for display in the UI
 */
export const BUSINESS_TYPE_LABELS: Record<(typeof BUSINESS_TYPES)[keyof typeof BUSINESS_TYPES], string> = {
  [BUSINESS_TYPES.DENTAL_PRACTICE]: "Dental Practice",
  [BUSINESS_TYPES.PERSONAL_CUSTOMER]: "Personal Customer",
  [BUSINESS_TYPES.EDUCATIONAL_OR_GOVERNMENT_DENTAL_FACILITY]: "Educational or Government Dental Facility",
  [BUSINESS_TYPES.DENTAL_SERVICE_INDUSTRY]: "Dental Service Industry",
  [BUSINESS_TYPES.OTHER_HEALTHCARE_BUSINESS]: "Other Healthcare Business",
  [BUSINESS_TYPES.MANUFACTURER]: "Manufacturer",
  [BUSINESS_TYPES.TECHNOLOGY]: "Technology",
  [BUSINESS_TYPES.AEROSPACE]: "Aerospace",
  [BUSINESS_TYPES.SERVICE_INDUSTRY]: "Service Industry",
  [BUSINESS_TYPES.GOVERNMENT_AGENCY]: "Government Agency",
  [BUSINESS_TYPES.EDUCATION_SCHOOL_COLLEGES]: "Education (School / Colleges)",
  [BUSINESS_TYPES.NON_PROFIT_CHARITY]: "Non-profit / Charity",
  [BUSINESS_TYPES.SPORT_LEISURE]: "Sport & Leisure",
  [BUSINESS_TYPES.RELIGIOUS_SPIRITUAL]: "Religious / Spiritual",
  [BUSINESS_TYPES.OTHER]: "Other",
}

/**
 * Array of business types for easy iteration (e.g., in select options)
 */
export const BUSINESS_TYPE_OPTIONS = [
  {
    value: BUSINESS_TYPES.DENTAL_PRACTICE,
    label: BUSINESS_TYPE_LABELS[BUSINESS_TYPES.DENTAL_PRACTICE],
  },
  {
    value: BUSINESS_TYPES.PERSONAL_CUSTOMER,
    label: BUSINESS_TYPE_LABELS[BUSINESS_TYPES.PERSONAL_CUSTOMER],
  },
  {
    value: BUSINESS_TYPES.EDUCATIONAL_OR_GOVERNMENT_DENTAL_FACILITY,
    label: BUSINESS_TYPE_LABELS[BUSINESS_TYPES.EDUCATIONAL_OR_GOVERNMENT_DENTAL_FACILITY],
  },
  {
    value: BUSINESS_TYPES.DENTAL_SERVICE_INDUSTRY,
    label: BUSINESS_TYPE_LABELS[BUSINESS_TYPES.DENTAL_SERVICE_INDUSTRY],
  },
  {
    value: BUSINESS_TYPES.OTHER_HEALTHCARE_BUSINESS,
    label: BUSINESS_TYPE_LABELS[BUSINESS_TYPES.OTHER_HEALTHCARE_BUSINESS],
  },
  {
    value: BUSINESS_TYPES.MANUFACTURER,
    label: BUSINESS_TYPE_LABELS[BUSINESS_TYPES.MANUFACTURER],
  },
  {
    value: BUSINESS_TYPES.TECHNOLOGY,
    label: BUSINESS_TYPE_LABELS[BUSINESS_TYPES.TECHNOLOGY],
  },
  {
    value: BUSINESS_TYPES.AEROSPACE,
    label: BUSINESS_TYPE_LABELS[BUSINESS_TYPES.AEROSPACE],
  },
  {
    value: BUSINESS_TYPES.SERVICE_INDUSTRY,
    label: BUSINESS_TYPE_LABELS[BUSINESS_TYPES.SERVICE_INDUSTRY],
  },
  {
    value: BUSINESS_TYPES.GOVERNMENT_AGENCY,
    label: BUSINESS_TYPE_LABELS[BUSINESS_TYPES.GOVERNMENT_AGENCY],
  },
  {
    value: BUSINESS_TYPES.EDUCATION_SCHOOL_COLLEGES,
    label: BUSINESS_TYPE_LABELS[BUSINESS_TYPES.EDUCATION_SCHOOL_COLLEGES],
  },
  {
    value: BUSINESS_TYPES.NON_PROFIT_CHARITY,
    label: BUSINESS_TYPE_LABELS[BUSINESS_TYPES.NON_PROFIT_CHARITY],
  },
  {
    value: BUSINESS_TYPES.SPORT_LEISURE,
    label: BUSINESS_TYPE_LABELS[BUSINESS_TYPES.SPORT_LEISURE],
  },
  {
    value: BUSINESS_TYPES.RELIGIOUS_SPIRITUAL,
    label: BUSINESS_TYPE_LABELS[BUSINESS_TYPES.RELIGIOUS_SPIRITUAL],
  },
  {
    value: BUSINESS_TYPES.OTHER,
    label: BUSINESS_TYPE_LABELS[BUSINESS_TYPES.OTHER],
  },
] as const

/**
 * Type for business describe values
 */
export type BusinessType = (typeof BUSINESS_TYPES)[keyof typeof BUSINESS_TYPES]
