import {
  AlertTriangle,
  Award,
  Building,
  ChartBar,
  CheckCircle2,
  ClipboardList,
  Cog,
  Cookie,
  CreditCard,
  Database,
  FileText,
  Gavel,
  Handshake,
  Info,
  Lock,
  type LucideIcon,
  Monitor,
  MousePointer,
  Server,
  Shield,
  ShieldCheck,
  ShoppingBag,
  User,
  UserCog,
  Volume2,
} from "lucide-react"

export const iconMap: Record<string, LucideIcon> = {
  "file-contract": FileText,
  "shield-check": ShieldCheck,
  "user-md": User,
  handshake: Handshake,
  "shopping-bag": ShoppingBag,
  database: Database,
  "cookie-bite": Cookie,
  gavel: Gavel,
  certificate: Award,
  "clipboard-list": ClipboardList,
  user: User,
  "mouse-pointer": MousePointer,
  cog: Cog,
  lock: Lock,
  "shield-alt": Shield,
  building: Building,
  desktop: Monitor,
  server: Server,
  "chart-bar": ChartBar,
  bullhorn: Volume2,
  "user-cog": UserCog,
  "credit-card": CreditCard,
}

export const noticeIconMap: Record<string, LucideIcon> = {
  warning: AlertTriangle,
  success: CheckCircle2,
  info: Info,
  error: AlertTriangle,
}
