export type CustomerSegment = "High Value" | "Growth" | "At Risk" | "New"
export type CustomerHealth = "Healthy" | "Needs Attention" | "Dormant"

export interface VendorCustomer {
  id: string
  name: string
  clinicName: string
  email: string
  state: string
  city: string
  orders: number
  totalSpend: number
  averageOrderValue: number
  returnRate: number
  lastOrderDaysAgo: number
  segment: CustomerSegment
  health: CustomerHealth
  monthlyRevenue: number[]
}

export const VENDOR_CUSTOMERS: VendorCustomer[] = [
  {
    id: "dr-sarah-johnson",
    name: "Dr. Sarah Johnson",
    clinicName: "Johnson Dental Studio",
    email: "sarah.johnson@johnsondental.com",
    state: "California",
    city: "San Diego",
    orders: 48,
    totalSpend: 129400,
    averageOrderValue: 2696,
    returnRate: 82,
    lastOrderDaysAgo: 3,
    segment: "High Value",
    health: "Healthy",
    monthlyRevenue: [7600, 9200, 8800, 10400, 11200, 11700],
  },
  {
    id: "dr-michael-chen",
    name: "Dr. Michael Chen",
    clinicName: "Chen Orthodontics",
    email: "michael.chen@chenortho.com",
    state: "Texas",
    city: "Austin",
    orders: 43,
    totalSpend: 118600,
    averageOrderValue: 2758,
    returnRate: 79,
    lastOrderDaysAgo: 5,
    segment: "High Value",
    health: "Healthy",
    monthlyRevenue: [6900, 8400, 8600, 9200, 10100, 10800],
  },
  {
    id: "dr-emily-rodriguez",
    name: "Dr. Emily Rodriguez",
    clinicName: "BrightSmile Care",
    email: "emily.rodriguez@brightsmilecare.com",
    state: "Florida",
    city: "Miami",
    orders: 40,
    totalSpend: 109200,
    averageOrderValue: 2730,
    returnRate: 76,
    lastOrderDaysAgo: 4,
    segment: "High Value",
    health: "Healthy",
    monthlyRevenue: [6200, 7700, 8100, 8700, 9100, 9800],
  },
  {
    id: "dr-david-wilson",
    name: "Dr. David Wilson",
    clinicName: "Wilson Family Dentistry",
    email: "david.wilson@wilsonfamilydental.com",
    state: "New York",
    city: "Buffalo",
    orders: 36,
    totalSpend: 98750,
    averageOrderValue: 2743,
    returnRate: 74,
    lastOrderDaysAgo: 9,
    segment: "Growth",
    health: "Healthy",
    monthlyRevenue: [5600, 6400, 7100, 7600, 8200, 8800],
  },
  {
    id: "dr-olivia-brooks",
    name: "Dr. Olivia Brooks",
    clinicName: "Brookside Dental Group",
    email: "olivia.brooks@brookside-dental.com",
    state: "Illinois",
    city: "Chicago",
    orders: 34,
    totalSpend: 90500,
    averageOrderValue: 2662,
    returnRate: 73,
    lastOrderDaysAgo: 11,
    segment: "Growth",
    health: "Healthy",
    monthlyRevenue: [5100, 6000, 6700, 7100, 7600, 8200],
  },
  {
    id: "dr-james-murphy",
    name: "Dr. James Murphy",
    clinicName: "Murphy Dental Partners",
    email: "james.murphy@murphydental.com",
    state: "Arizona",
    city: "Phoenix",
    orders: 32,
    totalSpend: 84400,
    averageOrderValue: 2638,
    returnRate: 71,
    lastOrderDaysAgo: 6,
    segment: "Growth",
    health: "Healthy",
    monthlyRevenue: [4700, 5300, 6100, 6600, 7100, 7600],
  },
  {
    id: "dr-hannah-lee",
    name: "Dr. Hannah Lee",
    clinicName: "Lee Restorative Dental",
    email: "hannah.lee@leerestorative.com",
    state: "North Carolina",
    city: "Raleigh",
    orders: 30,
    totalSpend: 78500,
    averageOrderValue: 2617,
    returnRate: 69,
    lastOrderDaysAgo: 7,
    segment: "Growth",
    health: "Healthy",
    monthlyRevenue: [4300, 4900, 5600, 6100, 6500, 6900],
  },
  {
    id: "dr-nathan-price",
    name: "Dr. Nathan Price",
    clinicName: "Price Oral Care Center",
    email: "nathan.price@priceoralcare.com",
    state: "Colorado",
    city: "Denver",
    orders: 29,
    totalSpend: 75200,
    averageOrderValue: 2593,
    returnRate: 68,
    lastOrderDaysAgo: 13,
    segment: "Growth",
    health: "Needs Attention",
    monthlyRevenue: [3900, 4800, 5300, 5700, 6200, 6500],
  },
  {
    id: "dr-grace-kim",
    name: "Dr. Grace Kim",
    clinicName: "Kim Pediatric Dentistry",
    email: "grace.kim@kimpediatricdental.com",
    state: "California",
    city: "Irvine",
    orders: 27,
    totalSpend: 70100,
    averageOrderValue: 2596,
    returnRate: 66,
    lastOrderDaysAgo: 14,
    segment: "Growth",
    health: "Needs Attention",
    monthlyRevenue: [3500, 4100, 4900, 5300, 5700, 6100],
  },
  {
    id: "dr-ethan-patel",
    name: "Dr. Ethan Patel",
    clinicName: "Patel Smile Clinic",
    email: "ethan.patel@patelsmileclinic.com",
    state: "Texas",
    city: "Dallas",
    orders: 26,
    totalSpend: 66800,
    averageOrderValue: 2569,
    returnRate: 64,
    lastOrderDaysAgo: 18,
    segment: "Growth",
    health: "Needs Attention",
    monthlyRevenue: [3400, 3800, 4400, 5100, 5300, 5700],
  },
  {
    id: "dr-ava-morgan",
    name: "Dr. Ava Morgan",
    clinicName: "Morgan Dental Arts",
    email: "ava.morgan@morgandentalarts.com",
    state: "Florida",
    city: "Tampa",
    orders: 24,
    totalSpend: 61700,
    averageOrderValue: 2571,
    returnRate: 62,
    lastOrderDaysAgo: 19,
    segment: "Growth",
    health: "Needs Attention",
    monthlyRevenue: [2800, 3400, 3900, 4400, 5000, 5400],
  },
  {
    id: "dr-lucas-bennett",
    name: "Dr. Lucas Bennett",
    clinicName: "Bennett Advanced Dental",
    email: "lucas.bennett@bennettdental.com",
    state: "Georgia",
    city: "Atlanta",
    orders: 22,
    totalSpend: 57200,
    averageOrderValue: 2600,
    returnRate: 61,
    lastOrderDaysAgo: 23,
    segment: "At Risk",
    health: "Needs Attention",
    monthlyRevenue: [2900, 3200, 3800, 3700, 3400, 3000],
  },
  {
    id: "dr-amelia-scott",
    name: "Dr. Amelia Scott",
    clinicName: "Scott Dental Hub",
    email: "amelia.scott@scottdentalhub.com",
    state: "Washington",
    city: "Seattle",
    orders: 21,
    totalSpend: 53900,
    averageOrderValue: 2567,
    returnRate: 59,
    lastOrderDaysAgo: 27,
    segment: "At Risk",
    health: "Needs Attention",
    monthlyRevenue: [2700, 3000, 3600, 3400, 2900, 2600],
  },
  {
    id: "dr-daniel-foster",
    name: "Dr. Daniel Foster",
    clinicName: "Foster Family Dental",
    email: "daniel.foster@fosterfamilydental.com",
    state: "Oregon",
    city: "Portland",
    orders: 20,
    totalSpend: 51400,
    averageOrderValue: 2570,
    returnRate: 58,
    lastOrderDaysAgo: 31,
    segment: "At Risk",
    health: "Dormant",
    monthlyRevenue: [2600, 2800, 3300, 2900, 2500, 2100],
  },
  {
    id: "dr-claire-adams",
    name: "Dr. Claire Adams",
    clinicName: "Adams Endodontics",
    email: "claire.adams@adamsendo.com",
    state: "Massachusetts",
    city: "Boston",
    orders: 19,
    totalSpend: 48700,
    averageOrderValue: 2563,
    returnRate: 56,
    lastOrderDaysAgo: 34,
    segment: "At Risk",
    health: "Dormant",
    monthlyRevenue: [2500, 2700, 3000, 2600, 2200, 1900],
  },
  {
    id: "dr-alex-ramirez",
    name: "Dr. Alex Ramirez",
    clinicName: "Ramirez Dental Practice",
    email: "alex.ramirez@ramirezdental.com",
    state: "Nevada",
    city: "Las Vegas",
    orders: 18,
    totalSpend: 46200,
    averageOrderValue: 2567,
    returnRate: 54,
    lastOrderDaysAgo: 38,
    segment: "At Risk",
    health: "Dormant",
    monthlyRevenue: [2300, 2600, 2800, 2500, 2000, 1800],
  },
  {
    id: "dr-zoe-carter",
    name: "Dr. Zoe Carter",
    clinicName: "Carter Cosmetic Dentistry",
    email: "zoe.carter@cartercosmeticdental.com",
    state: "Tennessee",
    city: "Nashville",
    orders: 17,
    totalSpend: 43800,
    averageOrderValue: 2576,
    returnRate: 53,
    lastOrderDaysAgo: 12,
    segment: "New",
    health: "Healthy",
    monthlyRevenue: [1200, 1600, 2400, 3200, 3900, 4600],
  },
  {
    id: "dr-william-ross",
    name: "Dr. William Ross",
    clinicName: "Ross Dental Specialists",
    email: "william.ross@rossdentalspecialists.com",
    state: "Ohio",
    city: "Columbus",
    orders: 16,
    totalSpend: 41300,
    averageOrderValue: 2581,
    returnRate: 51,
    lastOrderDaysAgo: 10,
    segment: "New",
    health: "Healthy",
    monthlyRevenue: [900, 1500, 2300, 2900, 3500, 4200],
  },
  {
    id: "dr-evelyn-nguyen",
    name: "Dr. Evelyn Nguyen",
    clinicName: "Nguyen Dental Co.",
    email: "evelyn.nguyen@nguyendentalco.com",
    state: "Virginia",
    city: "Richmond",
    orders: 15,
    totalSpend: 38900,
    averageOrderValue: 2593,
    returnRate: 49,
    lastOrderDaysAgo: 16,
    segment: "New",
    health: "Needs Attention",
    monthlyRevenue: [700, 1200, 1800, 2400, 3200, 3800],
  },
  {
    id: "dr-sebastian-hill",
    name: "Dr. Sebastian Hill",
    clinicName: "Hill Orthodontic Works",
    email: "sebastian.hill@hillorthoworks.com",
    state: "Michigan",
    city: "Detroit",
    orders: 14,
    totalSpend: 36100,
    averageOrderValue: 2578,
    returnRate: 47,
    lastOrderDaysAgo: 21,
    segment: "New",
    health: "Needs Attention",
    monthlyRevenue: [600, 1000, 1500, 2100, 2900, 3500],
  },
  {
    id: "dr-mia-turner",
    name: "Dr. Mia Turner",
    clinicName: "Turner Dental Point",
    email: "mia.turner@turnerdentalpoint.com",
    state: "Minnesota",
    city: "Minneapolis",
    orders: 13,
    totalSpend: 33600,
    averageOrderValue: 2585,
    returnRate: 46,
    lastOrderDaysAgo: 24,
    segment: "New",
    health: "Needs Attention",
    monthlyRevenue: [500, 800, 1300, 1900, 2600, 3200],
  },
  {
    id: "dr-aiden-morris",
    name: "Dr. Aiden Morris",
    clinicName: "Morris Dental Network",
    email: "aiden.morris@morrisdentalnetwork.com",
    state: "Missouri",
    city: "St. Louis",
    orders: 12,
    totalSpend: 31200,
    averageOrderValue: 2600,
    returnRate: 44,
    lastOrderDaysAgo: 29,
    segment: "New",
    health: "Dormant",
    monthlyRevenue: [400, 700, 1200, 1600, 2100, 2600],
  },
  {
    id: "dr-sophia-garcia",
    name: "Dr. Sophia Garcia",
    clinicName: "Garcia Smile Center",
    email: "sophia.garcia@garciasmilecenter.com",
    state: "Pennsylvania",
    city: "Pittsburgh",
    orders: 11,
    totalSpend: 28900,
    averageOrderValue: 2627,
    returnRate: 42,
    lastOrderDaysAgo: 35,
    segment: "At Risk",
    health: "Dormant",
    monthlyRevenue: [600, 900, 1300, 1400, 1200, 1000],
  },
  {
    id: "dr-logan-baker",
    name: "Dr. Logan Baker",
    clinicName: "Baker Prosthodontics",
    email: "logan.baker@bakerprosthodontics.com",
    state: "Utah",
    city: "Salt Lake City",
    orders: 10,
    totalSpend: 26700,
    averageOrderValue: 2670,
    returnRate: 40,
    lastOrderDaysAgo: 42,
    segment: "At Risk",
    health: "Dormant",
    monthlyRevenue: [700, 800, 900, 1100, 900, 700],
  },
]

export const CUSTOMER_SEGMENTS: CustomerSegment[] = ["High Value", "Growth", "At Risk", "New"]
export const CUSTOMER_HEALTH: CustomerHealth[] = ["Healthy", "Needs Attention", "Dormant"]

export function formatLastOrder(daysAgo: number) {
  if (daysAgo <= 1) return "Today"
  return `${daysAgo}d ago`
}

export function getCustomerById(customerId: string) {
  return VENDOR_CUSTOMERS.find((customer) => customer.id === customerId)
}

export function getCustomerSegmentDistribution() {
  const total = VENDOR_CUSTOMERS.length
  return CUSTOMER_SEGMENTS.map((segment) => {
    const count = VENDOR_CUSTOMERS.filter((customer) => customer.segment === segment).length
    return {
      segment,
      count,
      share: Math.round((count / total) * 100),
    }
  })
}
