export interface VendorReview {
  id: string
  productId: string
  productName: string
  rating: number
  title: string
  comment: string
  reviewerName: string
  reviewerClinic: string
  createdDate: string
  verifiedPurchase: boolean
}

export const VENDOR_REVIEWS: VendorReview[] = [
  {
    id: "rv-001",
    productId: "prd-101",
    productName: "Premium Composite Kit",
    rating: 5,
    title: "Excellent consistency and finish",
    comment: "Application is smooth and polish quality is excellent. We reordered twice this month.",
    reviewerName: "Dr. Sarah Johnson",
    reviewerClinic: "Johnson Dental Studio",
    createdDate: "2026-04-28T10:35:00.000Z",
    verifiedPurchase: true,
  },
  {
    id: "rv-002",
    productId: "prd-102",
    productName: "Digital Intraoral Camera",
    rating: 5,
    title: "Image quality is top tier",
    comment: "Clear visuals and quick setup. Great support material included.",
    reviewerName: "Dr. Michael Chen",
    reviewerClinic: "Chen Orthodontics",
    createdDate: "2026-04-24T13:40:00.000Z",
    verifiedPurchase: true,
  },
  {
    id: "rv-003",
    productId: "prd-103",
    productName: "Surgical Instrument Set",
    rating: 4,
    title: "Reliable daily set",
    comment: "Solid build and easy sterilization. One handle felt slightly stiff initially.",
    reviewerName: "Dr. Emily Rodriguez",
    reviewerClinic: "BrightSmile Care",
    createdDate: "2026-04-21T09:18:00.000Z",
    verifiedPurchase: true,
  },
  {
    id: "rv-004",
    productId: "prd-104",
    productName: "Metal Bracket System",
    rating: 4,
    title: "Good value",
    comment: "Bonding performance is stable. Packaging can be improved for faster chairside flow.",
    reviewerName: "Dr. David Wilson",
    reviewerClinic: "Wilson Family Dentistry",
    createdDate: "2026-04-18T11:05:00.000Z",
    verifiedPurchase: true,
  },
  {
    id: "rv-005",
    productId: "prd-105",
    productName: "Endodontic File Pack",
    rating: 3,
    title: "Average durability",
    comment: "Works fine for standard cases. Expected a bit more lifespan under heavy use.",
    reviewerName: "Dr. Olivia Brooks",
    reviewerClinic: "Brookside Dental Group",
    createdDate: "2026-04-14T08:47:00.000Z",
    verifiedPurchase: true,
  },
  {
    id: "rv-006",
    productId: "prd-101",
    productName: "Premium Composite Kit",
    rating: 5,
    title: "Patient esthetics improved",
    comment: "Shade matching is very predictable. Team feedback is consistently positive.",
    reviewerName: "Dr. James Murphy",
    reviewerClinic: "Murphy Dental Partners",
    createdDate: "2026-04-11T15:30:00.000Z",
    verifiedPurchase: true,
  },
  {
    id: "rv-007",
    productId: "prd-106",
    productName: "Ultrasonic Scaler Tips",
    rating: 4,
    title: "Stable performance",
    comment: "Compatible and effective. Shipping arrived two days later than expected.",
    reviewerName: "Dr. Hannah Lee",
    reviewerClinic: "Lee Restorative Dental",
    createdDate: "2026-04-07T12:10:00.000Z",
    verifiedPurchase: true,
  },
  {
    id: "rv-008",
    productId: "prd-102",
    productName: "Digital Intraoral Camera",
    rating: 5,
    title: "Fast training curve",
    comment: "Assistants adopted it in one day. Integration with documentation workflow is smooth.",
    reviewerName: "Dr. Nathan Price",
    reviewerClinic: "Price Oral Care Center",
    createdDate: "2026-04-05T17:22:00.000Z",
    verifiedPurchase: true,
  },
  {
    id: "rv-009",
    productId: "prd-107",
    productName: "Temporary Crown Material",
    rating: 4,
    title: "Consistent handling",
    comment: "Good viscosity and easy trimming. Curing time is acceptable.",
    reviewerName: "Dr. Grace Kim",
    reviewerClinic: "Kim Pediatric Dentistry",
    createdDate: "2026-04-01T14:02:00.000Z",
    verifiedPurchase: true,
  },
  {
    id: "rv-010",
    productId: "prd-108",
    productName: "Suction System Filter Kit",
    rating: 2,
    title: "Not ideal for high-volume clinics",
    comment: "Frequent replacement needed. We switched part of usage to an alternative.",
    reviewerName: "Dr. Ethan Patel",
    reviewerClinic: "Patel Smile Clinic",
    createdDate: "2026-03-29T10:51:00.000Z",
    verifiedPurchase: true,
  },
]
