import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Toaster } from "sonner"
import "./globals.css"
import ConditionalFooter from "./components/ConditionalFooter"
import ConditionalNavbar from "./components/ConditionalNavbar"

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <ConditionalNavbar />
        {children}
        <ConditionalFooter />
        <Toaster position="top-right" richColors />
      </body>
    </html>
  )
}
