import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { cookies } from "next/headers"
import { Toaster } from "sonner"
import "./globals.css"
import AuthHydration from "./components/AuthHydration"
import ConditionalFooter from "./components/ConditionalFooter"
import ConditionalNavbar from "./components/ConditionalNavbar"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // Read auth cookie for SSR
  const cookieStore = await cookies()
  const authCookie = cookieStore.get("auth-storage")
  let initialState = null

  if (authCookie) {
    try {
      const decodedValue = decodeURIComponent(authCookie.value)
      const parsed = JSON.parse(decodedValue)
      initialState = parsed?.state || null
    } catch {
      // Ignore parsing errors
    }
  }

  return (
    <html lang="en">
      <body className={`${inter.className}`} suppressHydrationWarning>
        <AuthHydration />
        <ConditionalNavbar initialAuthState={initialState} />
        {children}
        <ConditionalFooter />
        <Toaster position="top-right" richColors />
      </body>
    </html>
  )
}
